### ISSUE TITLE
Expose Streamlit to the "world"

### ISSUE THREAD

**Issue by DaBeIDS** [os-climate/osc-transformer-presteps#47]
How could we make the streamlit app which just extracts data from pdf without ML available?

- [ ] Pre step is a Dockerfile (Dockerfile needed https://github.com/os-climate/osc-transformer-presteps/issues/40)
- [ ]  Create a route
- [ ]  Create a sign on restriction

**Comment by RishavIDS** [comment]
Shall we close this issue too @DaBeIDS ?

**Comment by DaBeIDS** [comment]
Correct the code goes to PyPi and will not need an own Dockerfile
