### ISSUE TITLE
Move curation code to new repo

### ISSUE THREAD

**Issue by DaBeIDS** [os-climate/osc-transformer-presteps#50]
Follow up to Add curation modules #41

Our goal is to transfer the curation of training data code to the new repository. This includes:

- [x] Add the code to the repo
- [x] Add tests for the code
- [ ] Add API endpoint to current api
- [x] Add a demo on how to use it
- [x] Add a description on how to use the curation

**Comment by RishavIDS** [comment]
Once PR is merged the curation will be added.

As for API endpoints, we are no longer doing that for curation as discussed.
